services:
  - type: web
    name: to-do-list
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cuuuk2a3esus73aein6g-a.oregon-postgres.render.com/to_do_app_lle0
      - key: SPRING_DATASOURCE_USERNAME
        value: to_do_app_lle0_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_postgres_password
      - key: JAVA_OPTS
        value: -Xmx512m
