services:
  - type: web
    name: to-do-list
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JAVA_OPTS
        value: -Xmx512m
